### ISSUE TITLE
No continuous builds

### ISSUE THREAD

**Issue by rob-smallshire** [pyserial/pyserial-asyncio#1]
We need to get Travis CI up and running on this repo, but first we need some tests to run.

**Comment by zsquareplusc** [comment]
I've set-up readthedocs.org and travis-ci.org as well as registered it on pypi.

The build on travis-ci currently fails with an import error, despite the fact that the dependencies (pyserial) are installed. However, it is installed as egg, which may be the root of the problem?

**Comment by rob-smallshire** [comment]
I'm looking into this. I think the problem is that the main serial package exports names such as 'serial_for_url' from its `__init__.py` which seems to be an issue with namespace packages. I think this is where the "prefer an empty `__init_.py` file" advice comes from.  That's clearly not an option in this case though.

**Comment by zsquareplusc** [comment]
The name `serial_asyncio` is also not bad. Actually `aio` was not very good but I tried to avoid import troubles, as `serial.asyncio` could not import the built-in `asyncio`.

re failing builds, I've added loop:// as device to run the test on, but the test_asyncio.py is currently only working with a real device. Well the actual problem is that the loop:// implementation is currently not asyncio compatible. If it s only small changes, the loop:// implementation could be updated. Otherwise it is also possible to add URL-handlers, so `pyserial_asyncio` could provide its own loop-asyncio:// handler.

**Comment by rob-smallshire** [comment]
I'll see if I can get an asyncio compatible loopback implementation working in the next few days.

**Comment by zsquareplusc** [comment]
back to the travis-ci build, I'm not sure if you have noticed that the build configuration was installing pySerial from pypi, so without the changes for a namespace package. So maybe it would work when git master would be used.

But having a separate package, with its own documentation etc. is probably also easier to understand for users. So, continuing with `serial_asyncio` as package name is OK for me.

**Comment by rob-smallshire** [comment]
Fixed by #19. Now uses a socket-based serial port. At this level of abstraction we don't really care whether it's a "real" serial port – only that pySerial is behaving as expected. This liberates us from loopback hardware and such like.
