### ISSUE TITLE
is there a way to hook into the write method and have it print exactly whats being written

### ISSUE THREAD

**Issue by bigal337** [pyserial/pyserial-asyncio#26]
I'm having a strange bug on my microcontroller and I need to verify that the data being sent is correct.

**Comment by rob-smallshire** [comment]
Not easily. Here are are couple of options:

1) [Easy. Inelegant.] Directly modify the source of pyserial-asyncio to add print statements as necessary.

2) [Laborious. Elegant]. Clone and modify `open_serial_connection()` so that instead of it creating the `Serial` instance with the call to `serial_for_url()` you arrange to pass in a `Serial` instance (Arguably, this would be a better design anyway).  You could then create a wrapper class which proxies the real `Serial` instance which logs traffic through the `write()` method to the `Serial` object.

Either way, you need to modify the pyserial-asyncio source, so I'd probably go with option 1.

**Comment by bigal337** [comment]
@rob-smallshire thank you

**Comment by zsquareplusc** [comment]
If `serial_for_url`is used, try the [spy protocol](https://pyserial.readthedocs.io/en/latest/url_handlers.html#spy). not sure how well it works with asyncio, but i think read and write are still called, so it should work.

**Comment by zsquareplusc** [comment]
And for Rob's tip 2, if you want to have an own Serial class called, monkeypatch it into the serial module and then select using the [alt protocol](https://pyserial.readthedocs.io/en/latest/url_handlers.html#alt)

e.g. `serial.MySerial = MySerial` then `alt:///dev/ttyUSB0?class=MySerial` should work.

but for simple spy functionality, see last comment about `spy://`

**Comment by rob-smallshire** [comment]
@zsquareplusc Top tips!
