### ISSUE TITLE
Higher level API that matches pyserial

### ISSUE THREAD

**Issue by kasbah** [pyserial/pyserial-asyncio#32]
Hey, I am excited for asyncio support for pyserial as our [Braille E-Book reader](https://github.com/Bristol-Braille/canute-ui) uses pyserial as it's main communication link to the display. 

Having used [aiofiles](https://github.com/Tinche/aiofiles) I was expecting an API like this (for python 3.5+):

```python
async with serial_asyncio.Serial('/dev/ttyS1', 19200, timeout=1) as ser:
     x = await ser.read()          
     s = await ser.read(10)  
     line = await ser.readline()  
     await ser.write(b'hello') 
```

Is something like this planned?

**Comment by zmitchell** [comment]
See #35, you can actually do this with [`trio`](https://github.com/python-trio/trio) and `trio.wrap_file()` as long as you're aware that the device can become unresponsive in some cases.

**Comment by rob-smallshire** [comment]
Streams are supported with the `open_serial_connection` function:

```python3
reader, writer = open_serial_connection(loop=loop, port='/dev/ttyS1', baudrate=19200, timeout=1)
x = await reader.read()
s = await reader.read(10)
line = await reader.readline()
await writer.write(b'hello')
```

**Comment by septatrix** [comment]
Maybe we should add an example like this to the documentation (I have not yet looked at what you added a few days ago). I think more people would want to use the this syntax instead of creating custom protocols.
Also see e.g. https://github.com/changyuheng/aioserial/commit/983ac4707a84aa18b8cc29697c04841503617252 which (understandably) took the example from the docs and made a comparison. While protocols are very powerful many people are more inclined to the stream variant...
